spring:
  # Data source configuration
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/hunters_league_db
  #   username: admin
  #   password: admin
  #   driver-class-name: org.postgresql.Driver

  # Docker compose configuration
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  # Liquibase configuration
  liquibase:
    change-log: db/changelog/master.yaml
    enabled: true

    # Exclude auto-configuration for security
    #autoconfigure:
    # exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # Mail properties
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${SUPPORT_USERNAME}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  # Optional external configuration file import
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none

# JWT security configuration
security:
  jwt:
    access-secret-key: ${JWT_ACCESS_SECRET_KEY}
    refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
    access-expiration-time: 120000
    refresh-expiration-time: 604800000
