name: qliky
services:
  postgres:
    container_name: bidderx
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bidderx'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=qliky'
    ports:
      - '5433:5432'
volumes:
  postgres_data:
    driver: local